#!/usr/bin/env python3
"""
make_icons.py — convert app icons in resources/ to a RGB565 C header.

Writes src/icons_data.h (included by src/icons.c to replace geometric placeholders).

Usage:
    python3 tools/make_icons.py [--size N]   # default size = 32

Requirements:
    pip3 install Pillow
    pip3 install cairosvg   # only needed for the Chrome SVG icon

RGB565 values are byte-swapped (big-endian) to match the framebuffer layout
used by lcd_flush_* (see LCD_W macro and RGB565() in lcd.h).
"""

import sys
import io
import argparse
from pathlib import Path

# ── Icon manifest ──────────────────────────────────────────────────────────────
# Maps C symbol name → resource filename (relative to resources/).
# Order must match ICON_xxx defines in src/profiles.h.

ICONS = [
    ("ICON_CHROME", "Google_Chrome_icon_(February_2022).svg"),
    ("ICON_CLAUDE", "Claude_icon.png"),
    ("ICON_FUSION", "fusion-360-product-design-extension-2023-simplified-badge-75x75.png.webp"),
    ("ICON_KICAD",  "kicad.png"),
    ("ICON_KRITA",  "Calligra_Krita_icon.svg.png"),
]

# ── Conversion helpers ─────────────────────────────────────────────────────────

def rgb565_bswap(r, g, b):
    """RGB888 → RGB565, then byte-swap for SPI/DMA big-endian output."""
    v = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    return ((v & 0xFF) << 8) | ((v >> 8) & 0xFF)

def open_image(path: Path, size: int):
    """Open any supported image, return a PIL Image in RGB mode at (size×size)."""
    from PIL import Image

    if path.suffix.lower() == ".svg":
        try:
            import cairosvg
        except ImportError:
            raise SystemExit(
                f"cairosvg is required for SVG files.\n"
                f"  pip3 install cairosvg\n"
                f"or pre-rasterise with:\n"
                f"  rsvg-convert -w {size} -h {size} '{path}' -o /tmp/icon.png\n"
                f"then rename the result to '{path.name[:-4]}.png' in resources/"
            )
        png_bytes = cairosvg.svg2png(
            url=str(path.resolve()), output_width=size, output_height=size
        )
        img = Image.open(io.BytesIO(png_bytes))
    else:
        img = Image.open(path)

    # Composite RGBA onto a black background, then resize
    img = img.convert("RGBA")
    if img.size != (size, size):
        img = img.resize((size, size), Image.LANCZOS)
    bg = Image.new("RGBA", (size, size), (0, 0, 0, 255))
    bg.paste(img, mask=img.split()[3])
    return bg.convert("RGB")

def image_to_c_array(img, name: str, size: int) -> str:
    """Return a C uint16_t array literal for the image."""
    pixels = list(img.getdata())
    values = [rgb565_bswap(r, g, b) for r, g, b in pixels]

    data_name = f"icon_data_{name[5:].lower()}"   # ICON_CHROME → icon_data_chrome
    lines = [f"// {name}: {size}×{size} RGB565 (byte-swapped)"]
    lines.append(f"static const uint16_t {data_name}[{size * size}] = {{")
    for row in range(size):
        chunk = values[row * size : (row + 1) * size]
        lines.append("    " + ", ".join(f"0x{v:04X}" for v in chunk) + ",")
    lines.append("};")
    return "\n".join(lines)

# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--size", type=int, default=32, help="Icon pixel size (default 32)")
    args = parser.parse_args()

    root     = Path(__file__).parent.parent   # project root
    res_dir  = root / "resources"
    out_path = root / "src" / "icons_data.h"

    try:
        from PIL import Image  # noqa: F401
    except ImportError:
        raise SystemExit("Pillow is required: pip3 install Pillow")

    size = args.size
    blocks = []
    failed = []

    for cname, fname in ICONS:
        src = res_dir / fname
        if not src.exists():
            print(f"  MISSING  {fname}", file=sys.stderr)
            failed.append(cname)
            continue
        try:
            img = open_image(src, size)
            blocks.append(image_to_c_array(img, cname, size))
            print(f"  OK       {fname} → {cname.lower()}[{size*size}]")
        except SystemExit as e:
            print(f"  SKIP     {fname}: {e}", file=sys.stderr)
            failed.append(cname)
        except Exception as e:
            print(f"  ERROR    {fname}: {e}", file=sys.stderr)
            failed.append(cname)

    if not blocks:
        raise SystemExit("No icons converted — check errors above.")

    defines = "\n".join(f"#define ICON_DATA_{n.replace('ICON_','')} 1" for n, _ in ICONS if n not in failed)

    header = "\n".join([
        "// Auto-generated by tools/make_icons.py — do not edit by hand.",
        f"// Icon size: {size}×{size} px, RGB565 byte-swapped.",
        "// Regenerate: python3 tools/make_icons.py",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define ICON_DATA_SIZE {size}",
        "",
        "// Present-icon flags (used by icons.c to select real vs geometric)",
        defines,
        "",
    ] + [b + "\n" for b in blocks])

    out_path.write_text(header)
    print(f"\nWrote {out_path.relative_to(root)}")
    if failed:
        print(f"Skipped: {', '.join(failed)} — geometric fallback will be used.")

if __name__ == "__main__":
    main()
